services:
  odoo:
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "8069:8069"
    user: "${UID}:${GID}"
    environment:
      ODOO_DB_HOST: ${DB_HOST:-odoo_db}
      ODOO_DB_PORT: ${DB_PORT:-5432}
      ODOO_DB_USER: ${DB_USER:-odoo}
      ODOO_DB_PASSWORD: ${DB_PASSWORD:-odoo}
    volumes:
      - ./src/odoo.conf:/volumes/config/odoo.conf
      - ./tests/config:/volumes/config
      - ./addons:/volumes/addons
      - ./hooks:/hooks
      - odoo_data:/volumes/data
      # Uncomment this to add enterprise at run-time:
#      - ./enterprise:/volumes/enterprise
    depends_on:
      odoo_db:
        condition: service_healthy
  odoo_db:
    image: postgres:13
    container_name: odoo_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-odoo}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-odoo}
      POSTGRES_DB: ${POSTGRES_DATABASE:-postgres}
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 12
    ports:
      - "5432:5432"

volumes:
  odoo_data:
  pg_data:
